# This is a basic workflow to help you get started with Actions

name: Simple Manual Workflow

# Controls when the workflow will run
on:
  #Allows you to run this workflow manually from the Actions Tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  develop:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Environment which it will run on 
    environment: develop
    # Steps represent a sequence of tasks that will be executed as part of the job
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Run a script
        run: echo " I am running a job in the dev environment"
        
  staging:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Environment which it will run on 
    environment: staging
    # Steps represent a sequence of tasks that will be executed as part of the job
    needs: develop
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Run a script
        run: echo " I am running a job in the staging environment"
        
  production:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Environment which it will run on 
    environment: production
    # Steps represent a sequence of tasks that will be executed as part of the job
    needs: staging
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Run a script
        run: echo " I am running a job in the production environment"

